### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by caitlin-woodside** [Jonathan-Livingston-Seagull/AutoCalibration#2]
Hi, I would like to use and modify your code, but you have not added a license, so as per GitHub (https://choosealicense.com/no-permission/#for-users), I am not able to. 

Would you be open to adding a license? BSD or MIT would be great - I noticed you have used them for other repositories.

Thanks!

**Comment by s-udhaya** [comment]
@caitlin-woodside Added the License. Have fun!
